apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudprober-deployment.yaml
- cloudprober-service.yaml
- cloudprober-ingress.yaml
configMapGenerator:
- name: cloudprober-config
  files:
  - configs/cloudprober.cfg
