apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudmonitor-am
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmonitor-am
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloudmonitor-am
    spec:
      containers:
        - args:
            - --config.file=/etc/alertmanager.yml
          image: prom/alertmanager:v0.23.0
          name: alertmanager
          resources: {}
          volumeMounts:
            - mountPath: /etc/alertmanager.yml
              name: am-cfg
              subPath: alertmanager.yml
      restartPolicy: Always
      volumes:
        - name: am-cfg
          configMap:
            name: alertmanager-config
status: {}
