apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cloudprober
  name: cloudprober
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudprober
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cloudprober
    spec:
      containers:
        - image: cloudprober/cloudprober:v0.11.9
          name: cloudprober
          args: [
                  "--logtostderr"
                ]
          volumeMounts:
            - mountPath: /etc/cloudprober.cfg
              subPath: cloudprober.cfg
              name: prober-config
      restartPolicy: Always
      volumes:
        - name: prober-config
          configMap:
            name: cloudprober-config
status: {}
