apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus-deployment.yaml
- prometheus-service.yaml
- prometheus-ingress.yaml
configMapGenerator:
- name: prometheus-config
  files:
  - configs/alert.rules
  - configs/prometheus.yml
