apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanager-deployment.yaml
- alertmanager-service.yaml
- alertmanager-ingress.yaml
configMapGenerator:
- name: alertmanager-config
  files:
  - configs/alertmanager.yml
